export const ERROR_CODES = {
  // Errores Generales (GEN)
  GEN_INTERNAL_ERROR: 'GEN_001',
  GEN_VALIDATION_ERROR: 'GEN_002',
  GEN_BAD_REQUEST: 'GEN_003',
  GEN_UNAUTHORIZED: 'GEN_004',
  GEN_FORBIDDEN: 'GEN_005',
  GEN_NOT_FOUND: 'GEN_006',
  GEN_CONFLICT: 'GEN_007',
  GEN_UNPROCESSABLE_ENTITY: 'GEN_008',

  // Errores de Base de Datos (DB)
  DB_CONNECTION_ERROR: 'DB_001',
  DB_QUERY_ERROR: 'DB_002',
  DB_CONSTRAINT_VIOLATION: 'DB_003',
  DB_DUPLICATE_ENTRY: 'DB_004',
  DB_FOREIGN_KEY_VIOLATION: 'DB_005',
  DB_TRANSACTION_ERROR: 'DB_006',

  // Errores de Autenticación (AUTH)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_TOKEN_MISSING: 'AUTH_004',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_005',
  AUTH_USER_NOT_FOUND: 'AUTH_006',
  AUTH_USER_INACTIVE: 'AUTH_007',

  // Errores de Series (SERIE)
  SERIE_NOT_FOUND: 'SERIE_001',
  SERIE_ALREADY_EXISTS: 'SERIE_002',
  SERIE_INVALID_GENRE: 'SERIE_003',
  SERIE_HAS_EPISODES: 'SERIE_004',
  SERIE_INACTIVE: 'SERIE_005',

  // Errores de Episodios (EP)
  EP_NOT_FOUND: 'EP_001',
  EP_SERIE_NOT_FOUND: 'EP_002',
  EP_DUPLICATE_NUMBER: 'EP_003',
  EP_INVALID_DURATION: 'EP_004',
  EP_SERIE_REQUIRED: 'EP_005',

  // Errores de Estados (EST)
  EST_NOT_FOUND: 'EST_001',
  EST_INVALID_IDENTIFIER: 'EST_002',
  EST_INACTIVE: 'EST_003',
  EST_IN_USE: 'EST_004',
};

export type ErrorCode = string;